project:
  type: website

website:
  title: "Meishu Zhao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Example_analysis.qmd
        text: Example Analysis

format:
  html:
    theme: lux
    css: styles.css
    toc: true



